#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(USERMANAGEMENTLIBRARY_LIB)
#  define USERMANAGEMENTLIBRARY_EXPORT Q_DECL_EXPORT
# else
#  define USERMANAGEMENTLIBRARY_EXPORT Q_DECL_IMPORT
# endif
#else
# define USERMANAGEMENTLIBRARY_EXPORT
#endif
